name: 🐛 Bug Report
description: Report a bug to help us improve n8n-mcp-modern
title: "[Bug]: "
labels: ["bug", "needs-triage"]
projects: ["eekfonky/n8n-mcp-modern"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! 🐛
        
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read the [documentation](https://github.com/eekfonky/n8n-mcp-modern/blob/main/README.md)
          required: true
        - label: I am using a supported Node.js version (≥22.0.0)
          required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of n8n-mcp-modern are you using?
      options:
        - Latest (main branch)
        - v5.2.8
        - v5.2.7
        - v5.2.6
        - v5.2.5
        - v5.2.4
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: In what environment are you experiencing this bug?
      options:
        - Claude Desktop (MCP)
        - Command line interface
        - Docker container
        - GitHub Codespaces
        - Other (specify in description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Configure with '...'
        3. Execute '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add error logs or screenshots
      placeholder: |
        Paste error logs here...
        
        Please set LOG_LEVEL=debug for more detailed logs
      render: shell

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: Information about your system
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 14.0, Windows 11]
        - Node.js: [e.g., v22.1.0]
        - NPM: [e.g., v10.5.0]
        - n8n version: [e.g., v1.32.0]
        - Claude Desktop version: [if applicable]
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration (remove sensitive information)
      placeholder: |
        ```json
        {
          "mcpServers": {
            "n8n-mcp": {
              "command": "...",
              "args": [...],
              "env": {...}
            }
          }
        }
        ```
      render: json

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context about the problem here...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help fix this bug?
      options:
        - label: I would like to work on fixing this bug
        - label: I can provide additional testing/debugging
        - label: I can help with documentation updates