version: '3.8'

services:
  n8n-mcp-modern:
    image: node:22-alpine
    working_dir: /app
    command: >
      sh -c "
        npm install -g @eekfonky/n8n-mcp-modern &&
        n8n-mcp
      "
    environment:
      - N8N_API_URL=https://your-n8n-instance.com
      - N8N_API_KEY=your-api-key-here
      - LOG_LEVEL=info
      - ENABLE_CACHE=true
      - NODE_ENV=production
    volumes:
      - mcp_data:/app/data
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  mcp_data:
    driver: local